Sorbet/Refinement:
  Enabled: pending

Sorbet/AllowIncompatibleOverride:
  Enabled: true

Sorbet/BindingConstantWithoutTypeAlias:
  Enabled: true

Sorbet/CallbackConditionalsBinding:
  Enabled: false

Sorbet/CheckedTrueInSignature:
  Enabled: true

Sorbet/EmptyLineAfterSig:
  Enabled: true

Sorbet/ConstantsFromStrings:
  Enabled: true

Sorbet/EnforceSigilOrder:
  Enabled: true

Sorbet/EnforceSingleSigil:
  Enabled: true

Sorbet/EnforceSignatures:
  Enabled: false

Sorbet/FalseSigil:
  Enabled: true

Sorbet/ForbidExtendTSigHelpersInShims:
  Enabled: true

Sorbet/ForbidRBIOutsideOfAllowedPaths:
  Enabled: true

Sorbet/ForbidIncludeConstLiteral:
  Enabled: false

Sorbet/ForbidTypeAliasedShapes:
  Enabled: false

Sorbet/ForbidSig:
  Enabled: false

Sorbet/ForbidSigWithRuntime:
  Enabled: false

Sorbet/ForbidSigWithoutRuntime:
  Enabled: false

Sorbet/ForbidSuperclassConstLiteral:
  Enabled: false

Sorbet/ForbidTEnum:
  Enabled: false

Sorbet/ForbidTStruct:
  Enabled: false

Sorbet/ForbidTUnsafe:
  Enabled: false

Sorbet/ForbidTUntyped:
  Enabled: false

Sorbet/ForbidUntypedStructProps:
  Enabled: true

Sorbet/HasSigil:
  Enabled: false

Sorbet/IgnoreSigil:
  Enabled: false

Sorbet/ImplicitConversionMethod:
  Enabled: false

Sorbet/KeywordArgumentOrdering:
  Enabled: true

Sorbet/ObsoleteStrictMemoization:
  Enabled: true

Sorbet/BuggyObsoleteStrictMemoization:
  Enabled: true

Sorbet/RedundantExtendTSig:
  Enabled: false

Sorbet/SignatureBuildOrder:
  Enabled: true

Sorbet/SingleLineRbiClassModuleDefinitions:
  Enabled: false

Sorbet/StrictSigil:
  Enabled: false

Sorbet/StrongSigil:
  Enabled: false

Sorbet/TrueSigil:
  Enabled: false

Sorbet/TypeAliasName:
  Enabled: true

Sorbet/ValidSigil:
  Enabled: true

Sorbet/VoidCheckedTests:
  Enabled: true

Sorbet/MultipleTEnumValues:
  Enabled: true

Sorbet/ForbidComparableTEnum:
  Enabled: true
